baseURL = 'https://anderspoirel.net/'
languageCode = 'en-us'
title = 'Anders Poirel'

enableGitInfo = true

[menu]
  [[menu.main]]
    name = "> anderspoirel.net"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "posts"
    url = "/posts"
    weight = 2
  [[menu.main]]
    name = "blogroll"
    url = "/blogroll"
    weight = 3
  [[menu.main]]
    name = "about"
    url = "/about"
    weight = 5


[markup]
  [markup.highlight]
    noClasses = false
